### ISSUE TITLE
windows crash?

### ISSUE THREAD

**Issue by GimoDDak** [br69ks/Hit-Registration-Fix#1]
sourcemod version and dhooks are using the latest version,
in Windows OS, my server crashes due to this plugin (I also tried sourcemod dev version but it still crashes)
there is nothing in the sourcemod error logs
can you fix this problem?

**Comment by br69ks** [comment]
I've removed the broken patches for now, gonna rewrite some stuff. This should still fix the max distance on windows which is useful for high velocity.
